### ISSUE TITLE
Add possibility to pass `env` variables, like System.cmd

### ISSUE THREAD

**Issue by philipgiuliani** [jayjun/rambo#2]
`System.cmd` has the possibility to pass a keyword list of `env` variables for executing the command.

See: https://github.com/elixir-lang/elixir/blob/v1.10.2/lib/elixir/lib/system.ex#L730

It would be nice to also have this feature in Rambo!

**Comment by jayjun** [comment]
`System.cmd` accepts a list of string-string tuples, not a keyword list.

```elixir
iex> Keyword.keyword?([{"MIX_ENV", "test"}])
false
```

Good news is, Rambo already accepts that and it‘s [documented](https://hexdocs.pm/rambo/0.3.1/Rambo.html#run/3-options)!

**Comment by philipgiuliani** [comment]
Oh, I looked for it but missed it 😅 Thank you!
