### ISSUE TITLE
Suitable for supervised long-running Python processes?

### ISSUE THREAD

**Issue by Maxximiliann** [jayjun/rambo#6]
It seems your solution may be just what we’ve been looking for.

Our Elixir project requires that we initiate and then supervise communications with a long-running, data streaming Python process. Data will be pushed to its Elixir counterpart about every second. Both processes are running on the same machine. 

Is Rambo a good match for this particular use case? If so, what recipes would you recommend?

**Comment by jayjun** [comment]
Not a good match, Rambo is meant for short-lived programs. Check out [Comparisons](https://github.com/jayjun/rambo#comparisons) in the README for better suited libraries.
