### ISSUE TITLE
Issue when terminating long-running process

### ISSUE THREAD

**Issue by benvp** [jayjun/rambo#7]
Hey, I have a long running process which get's killed after a certain amount of time automatically. The process get's correctly killed on the system, but somehow it doesn't allow the system process to do it's cleanup. How does rambo end the system processes when calling `kill`? The process in my case is `parec` which records system audio. However, when the process is killed by rambo the recording doesn't work as the `parec` doesn't seem to have enough time to end the recording properly (which it does if `SIGINT`, `SIGTERM` is being sent.). Any idea? I didn't really find anything which points in the right direction while browsing the code.

**Comment by jayjun** [comment]
Underneath, Rambo uses Rust’s [`Child::kill`](https://doc.rust-lang.org/std/process/struct.Child.html#method.kill) which does a SIGKILL.

When the Rust standard library or a cross-platform (including Windows) Cargo package supports SIGTERM, I can add it.

This is one of the reasons I do not recommend Rambo for long-running processes. Check out the [README](https://github.com/jayjun/rambo#comparisons) for alternatives.
