### ISSUE TITLE
No local return dialyzer issue

### ISSUE THREAD

**Issue by larshesel** [jayjun/rambo#8]
If I have `Rambo.run("echo")`  in my code, dialyzer will complain with a no local return error. 

This seems to be because `Rambo.run/1` calls  `Rambo.run/3` with the second argument set to `nil` (https://github.com/jayjun/rambo/blob/master/lib/rambo.ex#L66) which violates the `args() `  type of Rambo.run/3 (https://github.com/jayjun/rambo/blob/master/lib/rambo.ex#L14).

**Comment by jayjun** [comment]
Thanks for helpful investigation! Fixed in 0.3.3.
